### ISSUE TITLE
人脸对齐

### ISSUE THREAD

**Issue by Linsongrong** [elliottzheng/face-detection#1]
@elliottzheng 你好。请问项目里有人脸对齐功能吗？

**Comment by fedral** [comment]
![image](https://user-images.githubusercontent.com/13436512/99229673-461ce100-2829-11eb-9204-c4874bab3ef0.png)

调用的报错，请帮忙看一下。

**Comment by elliottzheng** [comment]
Hi, 那个pypi上的同名包已经不是这个仓库了，只能通过这个来安装
```
pip install git+https://github.com/elliottzheng/face-detection.git@master
```

**Comment by elliottzheng** [comment]
face alignment 可以看下这个 https://github.com/elliottzheng/batch-face/blob/master/tests/camera.py @Linsongrong

**Comment by Linsongrong** [comment]
@elliottzheng 谢谢啦
