### ISSUE TITLE
File mobilenet0.25_Final.pth is not packaged?

### ISSUE THREAD

**Issue by versae** [elliottzheng/face-detection#2]
After a fresh install using pip, the model weights file seems to be missing from the installation. My guess is that the `MANIFEST.in` needs to include files ending with `.pth` for pip install to work.

**Comment by elliottzheng** [comment]
Hi, this repo is deprecated, please check https://github.com/elliottzheng/batch-face, it has almost the same API and **it will download the weight from GitHub automatically for the first run.** You can also manually download weights from https://github.com/elliottzheng/face-detection/releases/download/0.0.1/mobilenet0.25_Final.pth and specify the path in the `RetinaFace` constructor as 
```
RetinaFace(model_path="mobilenet0.25_Final.pth")
```

**Comment by versae** [comment]
Awesome! Thanks.
